
// Project data export

export default [
    {
        title: "Online Canvas",
        description: "Currently in Development. A simple painting app that can be easily accessed from the web! Draw with a bunch of different colors and shapes then save your amazing artwork.",
        github: "https://github.com/nabarcala/Online-Canvas",
        website: "https://www.natsketch.com/",
        tech: ["React", "JavaScript", "HTML5", "CSS", "Canvas"],
        image: "canvas.gif",
        imgStart: true,
        top: true,
    }, 
    {
        title: "Portfolio V1",
        description: "First iteration of my personal portfolio website created with Python and Flask, where I organized the Flask application into modular components with Blueprints. Used a relational database management system to add, remove, and modify data.",
        github: "https://github.com/nabarcala/Python-and-Flask-Ex",
        website: "https://nb-portfolio.herokuapp.com/",
        tech: ["Python", "Flask"],
        image: "v1-mockup.png",
        // image: "v1.png",
        imgStart: false,
        top: false,
    },
    {
        title: "Current Weather Web App",
        description: "Currently in Development. Displays the current weather based on the user's geolocation. Allows the user to search for the weather of specific locations as well. This app pulls the weather data from the Open Weather Map API and displays it on the web app.",
        github: "https://github.com/nabarcala/Weather-App",
        website: "https://weather-app-nb.netlify.app/",
        tech: ["JavaScript", "HTML5", "CSS3", "Open Weather Map API"],
        image: "current-weather-mockup.png",
        // image: "current-weather.png",
        imgStart: true,
        top: false,
    },
    {
        title: "Medication Tracker",
        description: "Served as a front-end developer on a team of six to develop a web application that reminded the user of when they should take their medications. Able to create appointments with doctors logged into the web app. Integrated all appointments and medications into the site's calendar. Designed and converted mockups into code. Created the user interface.",
        github: "https://github.com/nabarcala/Medication-Tracker-Web-App",
        website: "",
        tech: ["PHP", "HTML", "CSS", "JavaScript"],
        image: "med-tracker.png",
        imgStart: false,
        top: false,
    },
    {
        title: "Lego Pill Sorter",
        description: "Participated in a three-person team to plan and create a pill sorter out of Legos. Programmed a Raspberry Pi to use a webcam to sort pills based on the color using OpenCV. Created a ramp on the device with two exits for the colored pills to roll through.",
        github: "https://github.com/nabarcala/PillSort",
        website: "",
        tech: ["Python", "OpenCV", "Raspberry Pi"],
        image: "lego.jpg",
        imgStart: true,
        top: false,
    },
    {
        title: "Senior Design Capstone Project",
        description: "Part of a team of three that created a fruit-slicing device equipped with a fruit identifier and ripeness detection system that is controlled by an accompanying Android app. Retrained a ResNet18 neural network to classify a specific set of fruits using an NVIDIA Jetson Nano, NVIDIA TensorRT, and PyTorch.",
        github: "https://github.com/nabarcala/SOFF",
        website: "",
        tech: ["Python", "Java", "PyTorch"],
        image: "soff.png",
        imgStart: false,
        top: true,
    },
];
